### ISSUE TITLE
如何把私钥从代码中剔除，移动到 Neuron 中？

### ISSUE THREAD

**Issue by happypeter** [happypeter/NervFirst#1]
目前，参考 https://github.com/cryptape/nervos-appchain-docs/blob/develop/zh-CN/quick-start/build-dapp.md ，我已经把合约部署到了 AppChain 上。

目前最大的一个问题是，私钥是写到代码中的。而我理解的理想状态时，私钥息应该是保存到 neuron 中的，每次 Dapp 代码，每次发送交易的时候，Neuron 都能负责签名。所以 Dapp 代码中应该不需要保存私钥的。

但是看 https://github.com/cryptape/dapp-demos/tree/develop/first-forever 的源码，私钥还是保存在 config.js 中的。

所以，请问有没有代码本身无私钥，签名由钱包完成的这样的 DApp 案例？或者是相关文档，neuron 的官方文档似乎还有待完善：https://docs.nervos.org/neuron-android/#/README 。

**Comment by Keith-CY** [comment]
在 dapp-demos 的 master 分支是适配 neuron 的代码

**Comment by happypeter** [comment]
thx
